### ISSUE TITLE
[1.5.2/1.6.4/1.7.2] Furnace GUI is buggy

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Shevchik/ProtocolSupport#18]
Screenshot: http://prntscr.com/6wh7gs

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by MrPowerGamerBR** [comment]
@Shevchik tried the new version, now causes a "Disconnected from the Server" when trying to open a Furnace (Tested in 1.7.X)

**Comment by Shevchik** [comment]
Try now, should be fixed

**Comment by burak-105** [comment]
I am still getting this error, even on latest version of protocolsupport
