### ISSUE TITLE
1.5.2 Clinet overturn entity and 1.6.X is crash

### ISSUE THREAD

**Issue by swan201** [Shevchik/ProtocolSupport#67]
Protocolsupport 4.20 is Fine. after 4.21DEV have probleum. but I cant tell you this probleum.

and 1.6.X crash Received string length is less than zero!
and other server 1.6.X client crash Received string  length longer than maximum allowed (69>16)

come to summerserver.ptcs.kr
and phgmy.ptcs.kr (1.6.X crash logner length)

**Comment by MrPowerGamerBR** [comment]
Can confirm, also, the string length varies. (In my Server, it says "java.io.IOException: Received string length longer than maximum allowed (85 > 16)")

Here's a Launcher log:
```
2015-10-18 13:58:56 [CLIENT] [INFO] Connecting to 127.0.0.1, 25565
java.io.IOException: Received string length longer than maximum allowed (85 > 16)
	at ey.a(SourceFile:240)
	at di.a(SourceFile:43)
	at ey.a(SourceFile:197)
	at co.i(SourceFile:249)
	at co.c(SourceFile:17)
	at cp.run(SourceFile:94)
```

**Comment by swan201** [comment]
@MrPowerGamerBR 

Yes, 1.5.2 Clinet doesn't happen it. but 1.5.2 clinet all spawn entity is overturn

**Comment by Shevchik** [comment]
Probably something wrong with player metadata, forgot to filter something, will check it.

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by MrPowerGamerBR** [comment]
@Shevchik still not working in the lastest dev build.

Now the error is different than before:
```
java.io.IOException: Received string length is less than zero! Weird string!
	at ey.a(SourceFile:243)
	at oo.a(SourceFile:271)
	at di.a(SourceFile:50)
	at ey.a(SourceFile:197)
	at co.i(SourceFile:249)
	at co.c(SourceFile:17)
	at cp.run(SourceFile:94)
```

**Comment by Shevchik** [comment]
Try now, 1.7 client needs testing now too.

**Comment by MrPowerGamerBR** [comment]
1.6.4: No client disconnection when viewing a player.
1.7.2: No client disconnection when viewing a player.

Fixed in the latest dev build. :smile: Thanks for your work @Shevchik (I would donate if I had a bit of money in my PayPal account, maybe in the near future :sunglasses:)

**Comment by swan201** [comment]
@Shevchik is isnt fix it lastest Dev Version. Still 1.5.2 Clinet See spawn entity is overturn. It look like updown graphics

**Comment by MrPowerGamerBR** [comment]
@swan201 I couldn't verify your issue (the 1.5.2 one) because I (and maybe even Shevchik) didn't understand what you are saying.

However, the 1.6.X one that you did report is fixed in the lastest dev build.

Could you share a screenshot of the "overturn entity" issue that you are having? This will help @Shevchik to fix the issue. Thanks :smiley:

**Comment by swan201** [comment]
![2015-10-20_03 47 16](https://cloud.githubusercontent.com/assets/12713262/10587713/5e531ee0-76dd-11e5-91e2-59573d5349fd.png)

sorry for my bad.. bad.. english. is just up and down to look. just i want to say :D

**Comment by MrPowerGamerBR** [comment]
@swan201 

...what is this? :open_mouth: 
![2015-10-19_16 46 21](https://cloud.githubusercontent.com/assets/9496359/10587696/104fd7e4-7681-11e5-9c98-f787127b94e3.png)
![2015-10-19_16 46 43](https://cloud.githubusercontent.com/assets/9496359/10587697/1055e094-7681-11e5-9889-3eabb7bc17cd.png)

I remember reading this issue on the Minecraft subreddit, however I don't recall what bug caused it (Maybe it is related to the #68 issue, IIRC, this bug happens when a invalid head is in a mob or player head, due to my issue being almost the same (when clicking a mob head in the 1.5.2 inventory, the client crashes due to a invalid NBT, your bug is caused because a skull is being loaded with a invalid NBT tag))

Launcher log:
```
`u: Reading NBT data
	at bs.i(SourceFile:163)
	at bht.a(SourceFile:163)
	at bht.c(SourceFile:23)
	at bho.a(SourceFile:134)
	at bht.a(SourceFile:130)
	at bht.a(SourceFile:23)
	at bgy.a(SourceFile:201)
	at bgy.a(SourceFile:181)
	at bfy.a(SourceFile:307)
	at bfq.a(SourceFile:894)
	at bfq.b(SourceFile:745)
	at net.minecraft.client.Minecraft.K(SourceFile:597)
	at net.minecraft.client.Minecraft.run(SourceFile:526)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: bs cannot be cast to ce
	at bs.i(SourceFile:161)
	... 13 more
```
This issue is caused by #68, a Skull Head with a invalid NBT crashes the client when clicking on it, and, if a 1.5.2 views a Skull Head on a Player or on a Entity, Minecraft starts rendering the world wrongly.

**Comment by MrPowerGamerBR** [comment]
Another thing, this issue also affects 1.6.X

**Comment by Shevchik** [comment]
Those are just bugs in OpenGL render caused by some items having worng data, like skulls for example.

**Comment by MrPowerGamerBR** [comment]
@Shevchik view the #68 issue, even newly created skulls with Essentials (or even with the default Minecraft command) causes this bug, the client tries to load a invalid NBT tag.

If you try to click/hold the skull, it crashes the client with the message "Invalid NBT tag".

If the client views (or it is wearing) a player with a custom skull, the render starts bugging out.

**Comment by swan201** [comment]
lets talk about this issue in here :) https://github.com/Shevchik/ProtocolSupport/issues/68
